security:
  encoders:
    BalticRobo\Website\Entity\User\User: bcrypt

  providers:
    user_login:
      entity:
        class: BalticRobo\Website\Entity\User\User
        property: email

  role_hierarchy:
    ROLE_SUPERADMIN:
    - ROLE_ADMIN
    - ROLE_CMS_ADMIN
    - ROLE_CMS_USER
    - ROLE_JUDGE
    - ROLE_COMPETITOR
    - ROLE_USER
    ROLE_CMS_ADMIN:
    - ROLE_CMS_USER
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    default:
      pattern: ^/
      anonymous: ~
      provider: user_login
      guard:
        authenticators:
        - BalticRobo\Website\Security\UserAuthenticator
      form_login:
        login_path: balticrobo_website_security_login
        check_path: balticrobo_website_security_login
        remember_me: true
      logout:
        path: balticrobo_website_security_logout
        target: balticrobo_website_security_login
