parameters:
  locale: en
  available_locales:
  - pl
  - en

framework:
  default_locale: '%locale%'
  translator:
    paths:
    - '%kernel.project_dir%/translations'
    fallbacks:
    - '%locale%'
    - pl
