webpack_encore:
  output_path: '%kernel.project_dir%/public/build'
  # if using Encore.enableIntegrityHashes() specify the crossorigin attribute value (default: false, or use 'anonymous' or 'use-credentials')
  #crossorigin: 'anonymous'
  cache: '%kernel.debug%'
