variables:
  TIMESTAMP: $(date +%s)
  CI_DATABASE_NAME: balticrobo_${TIMESTAMP}
  APP_ENV: test
  APP_SECRET: 7cbd4f1718b779f367516a8d917b6a29
  DATABASE_URL: mysql://${CI_DATABASE_USER}:${CI_DATABASE_PASSWORD}@127.0.0.1:3306/${CI_DATABASE_NAME}

stages:
  - Build (test)
  - Validate
  - Test
  - Quality analyze
  - Build (deploy)
  - Deploy

.cache:
  cache: &cache_definition
    paths:
      - vendor
      - node_modules
    policy: pull

Build for test:
  stage: Build (test)
  script:
    - composer install
    - yarn install
  cache:
    paths:
      - vendor
      - node_modules
    policy: pull-push

Lint Yaml:
  stage: Validate
  script:
    - bin/console lint:yaml config
    - bin/console lint:yaml translations
  cache: *cache_definition

Lint Twig:
  stage: Validate
  script:
    - bin/console lint:twig templates
  cache: *cache_definition

PHP_CodeSniffer:
  stage: Validate
  script:
    - vendor/bin/phpcs -p src
  allow_failure: true
  cache: *cache_definition

PHP-CS-Fixer:
  stage: Validate
  script:
    - vendor/bin/php-cs-fixer fix src --dry-run --diff -vvv
  allow_failure: true
  cache: *cache_definition

Composer Packages:
  stage: Validate
  script:
    - composer outdated
  allow_failure: true
  cache: *cache_definition

NPM Packages:
  stage: Validate
  script:
    - yarn outdated
  allow_failure: true
  cache: *cache_definition

Tests:
  stage: Test
  script:
    - echo ${DATABASE_URL}

Build prod:
  stage: Build (deploy)
  only:
    - master
    - develop
  artifacts:
    name: build
    expire_in: 1 week
    paths:
      - dist/
  variables:
    APP_ENV: prod
  script:
    - composer install --no-dev --optimize-autoloader
    - bin/console assets:install
    - yarn install
    - yarn build
    - mkdir -p dist
    - cp -r bin config public src templates translations vendor composer.json dist

Deploy develop:
  stage: Deploy
  only:
    - master
    - develop
  environment:
    name: staging
  variables:
    DEPLOY_HOST: $DEVELOP_HOST
    DEPLOY_DIRECTORY: $DEVELOP_DIRECTORY
  script:
    - rsync -razup --delete --exclude "var" --exclude ".env" --rsh="ssh -o BatchMode=yes -o StrictHostKeyChecking=no"
      . ${DEVELOP_HOST}:${DEVELOP_DIRECTORY}
    - ssh -o StrictHostKeyChecking=no ${DEVELOP_HOST} "
      php ${DEVELOP_DIRECTORY}/bin/console cache:clear &&
      php ${DEVELOP_DIRECTORY}/bin/console doctrine:migrations:migrate --no-interaction"
