variables:
  APP_ENV: test

stages:
  - Build (test)
  - Validate
  - Test
  - Quality analyze
  - Build (deploy)
  - Deploy

.common:
  tags: &tags_definition
    - php
    - node
  script: &deploy_definition
    - mkdir -p dist/var/cache
    - chmod -R 777 dist/var
    - rsync -a --delete --exclude ".env" --exclude "var" --rsh="ssh -o BatchMode=yes -o StrictHostKeyChecking=no"
      dist/ ${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
    - ssh -o StrictHostKeyChecking=no ${DEPLOY_HOST} "
      php ${DEPLOY_DIRECTORY}/bin/console cache:clear &&
      php ${DEPLOY_DIRECTORY}/bin/console cache:warmup &&
      php ${DEPLOY_DIRECTORY}/bin/console doctrine:migrations:migrate --no-interaction"
  cache: &cache_definition
    key: test
    paths:
      - vendor
      - node_modules
      - _email/node_modules
    policy: pull

Build for test:
  stage: Build (test)
  tags: *tags_definition
  script:
    - composer install
    - yarn install
    - cd _email && yarn install
  cache:
    key: test
    paths:
      - vendor
      - node_modules
      - _email/node_modules
    policy: pull-push

Lint Yaml:
  stage: Validate
  tags: *tags_definition
  script:
    - bin/console lint:yaml config
    - bin/console lint:yaml translations
  cache: *cache_definition

Lint Twig:
  stage: Validate
  tags: *tags_definition
  script:
    - bin/console lint:twig templates
  cache: *cache_definition

PHP_CodeSniffer:
  stage: Validate
  tags: *tags_definition
  script:
    - vendor/bin/phpcs -p src
  allow_failure: true
  cache: *cache_definition

PHP-CS-Fixer:
  stage: Validate
  tags: *tags_definition
  script:
    - vendor/bin/php-cs-fixer fix src --dry-run --diff -vvv
  allow_failure: true
  cache: *cache_definition

Composer Packages:
  stage: Validate
  tags: *tags_definition
  script:
    - composer outdated
  allow_failure: true
  cache: *cache_definition

NPM Packages:
  stage: Validate
  tags: *tags_definition
  script:
    - yarn outdated
    - cd _email && yarn outdated
  allow_failure: true
  cache: *cache_definition

Tests:
  stage: Test
  tags: *tags_definition
  variables:
    APP_ENV: test
    APP_SECRET: 7cbd4f1718b779f367516a8d917b6a29
  before_script:
    - export CI_DATABASE_NAME=gitlab_balticrobo_$(date +%s)
    - export DATABASE_URL=mysql://${CI_DATABASE_USER}:${CI_DATABASE_PASSWORD}@127.0.0.1:3306/${CI_DATABASE_NAME}
    - mysql -u${CI_DATABASE_USER} -p${CI_DATABASE_PASSWORD}
      -e "CREATE DATABASE ${CI_DATABASE_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  script:
    - echo 'Run tests! NOW!'
  after_script:
    - mysql -u${CI_DATABASE_USER} -p${CI_DATABASE_PASSWORD}
      -e "DROP DATABASE ${CI_DATABASE_NAME};"

Build prod:
  stage: Build (deploy)
  tags: *tags_definition
  only:
    - master
    - develop
  artifacts:
    name: build
    expire_in: 1 week
    paths:
      - dist/
  variables:
    APP_ENV: prod
  script:
    # symfony
    - composer install --no-dev --optimize-autoloader --no-scripts --no-suggest
    - bin/console assets:install
    # encore
    - yarn install
    - node assets.config.js
    - yarn build
    # inky
    - cd _email
    - yarn install
    - yarn build
    - cd ..
    # artifacts
    - mkdir -p dist
    - cp -r bin config public src templates translations vendor composer.json dist
  cache:
    key: deploy
    paths:
      - vendor
      - node_modules
      - _email/node_modules
    policy: pull-push

Deploy develop:
  stage: Deploy
  tags: *tags_definition
  only:
    - develop
  environment:
    name: staging
  variables:
    DEPLOY_HOST: $DEVELOP_HOST
    DEPLOY_DIRECTORY: $DEVELOP_DIRECTORY
    DEPLOY_EMAIL_ASSETS_DOMAIN: $DEVELOP_EMAIL_ASSETS_DOMAIN
  before_script:
    - 'echo User-agent: \* > dist/public/robots.txt'
    - 'echo Disallow: / >> dist/public/robots.txt'
  script: *deploy_definition

Deploy master:
  stage: Deploy
  tags: *tags_definition
  only:
    - master
  environment:
    name: production
  when: manual
  variables:
    DEPLOY_HOST: $PROD_HOST
    DEPLOY_DIRECTORY: $PROD_DIRECTORY
    DEPLOY_EMAIL_ASSETS_DOMAIN: $PROD_EMAIL_ASSETS_DOMAIN
  script: *deploy_definition
