language: minimal
sudo: required
services:
- docker
addons:
  ssh_known_hosts: balticrobo.eu

before_script:
- docker build -f .misc/docker-test/Dockerfile -t bbr_test_img .
- docker build -f .misc/docker-prod/Dockerfile -t bbr_prod_img .
script:
- docker run --name=bbr_test bbr_test_img
- docker rm bbr_test

before_deploy:
- docker create --name bbr_dist bbr_prod_img
- docker cp bbr_dist:/app ${TRAVIS_BUILD_DIR}/dist
- docker rm bbr_dist
- tar -zcf ${TRAVIS_BUILD_DIR}/dist.tar.gz ${TRAVIS_BUILD_DIR}/dist
- openssl aes-256-cbc -K ${encrypted_a54708e5d9c1_key} -iv ${encrypted_a54708e5d9c1_iv}
  -in ./.misc/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- "echo '{\"version\": \"'\"${TRAVIS_COMMIT}\"'\"}' > ${TRAVIS_BUILD_DIR}/version.json"
deploy:
- provider: script
  skip_cleanup: true
  script: >-
    rsync -a --delete --exclude ".env" --exclude "public/upload" --exclude "var" --rsh="ssh -o BatchMode=yes"
    ${TRAVIS_BUILD_DIR}/dist/ ${PROD_HOST}:${PROD_DIRECTORY} &&
    ssh ${PROD_HOST} "sed -i \"/COMMIT_SHA/c\COMMIT_SHA=${TRAVIS_COMMIT}\" ${PROD_DIRECTORY}/.env &&
    php ${PROD_DIRECTORY}/bin/console cache:clear --no-warmup &&
    php ${PROD_DIRECTORY}/bin/console cache:warmup &&
    php ${PROD_DIRECTORY}/bin/console doctrine:migrations:migrate --no-interaction" &&
    curl ${DEPLOY_SENTRY_RELEASE_WEBHOOK_ADDRESS}
      -X POST -H 'Content-Type: application/json' -d @${TRAVIS_BUILD_DIR}/version.json
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  file: ${TRAVIS_BUILD_DIR}/dist.tar.gz
  api_key:
    secure: SicrIqCm0LcWuHeAi57TsHLfwMiV+pXY+iFjdyDjGSWI6sDF1BMzwqRq4T/p47l0l3bQMF6Z8qxJciBtoL3fUqvpgfjuLcP0Epej0mHVLySP
      5NHBFZhKThXCEVl94SmtCqZmwlr575l8I8omuSSAOjAm44pgTLTcVNTWQuG27jGmHEJGoWmSoTWLNlFLw8T3YH2rFHRJbUsf0e5VIE0VGGVCCyX8qa
      tTS7TPVIaLTSYp607G0P8jBDm1JHX6Fqp+6goMayd85QM1Ag5AdJSGX2BvQ+9fyb0+42QPAxGM1mXOpsl1DLovpUz3YQDnWHBQXUVyonH+QrjmGlrL
      VF1q4yY8DokR997MSBsSSCcXJ+6odhBa60Uv3HSQF4Ick1LLYWEg2N5vqa9iSF55JJFE/pWrBmwc1c1kenCyxwWJPPUjr5zxQ+29OYSgB7l3MkzvBD
      uGInpaxskXLcRYIYNJF6Q6pWsvsMAEd4Y+TDLw4aO46QW5gg5mr8eQWJl4ahVV4kRAS30iVWWzn8PMZUTWHXsPGs9WNUnIgJ6GGl8olKicNjqlo7Ch
      cc3B8bnLuAD8x7QeU/Iqf+c0viWcTNzkgPDg+r23tWFW97FJQZIep2ZIbQ6AtK4tLa6bjcVrJIhDBmRCtqlo0x4HJXd6v1czAky0KQRWR6vOm4eO/q
      fPpmU=
  on:
    tags: true

notifications:
  slack:
    secure: eGgZrsc8yik1cknNQ2kCD5+Oq9rVThaxgsIWXk8VZJAc8mBjnrDBBzsWI1G/4r+aagOoZ47ru6vvSL9M8F5M8ZhFyv3LAXLiHDqHRW0twzul
      kbWiG12UKh2gmcbLDTGhcEtSUl0pwM3B/h3SGBYflDxbCxRnGtTgjHJJEuoUik8Yl9U/W5VJZvKRcsJw31hBPtJQRD93KqlxMxpWOcbCEWCz02H/xU
      LXVgykb3OtnelKSaWAIOqC3+MCKLFA4aWl9LquBdo0o8Xuwtf2hetaHF8rMdLIVJWYp8Q2a0WZS09CfJ9IqK/o9T2PxTd40ZGBwETGOAFeAobttsgy
      Yzr1CJOUdASk9BA/23d/Kop5Ilr5Kp5wEGFr6tTxsLgNxBqaHoYz/X2FYljRIsD0+Blxbzk78r2W7WZwrcvJD9REkUX/Sv171GNnLVTawloVdsY+/E
      qI34E874dtKNwLRneBTYVk0GoIXVNaOI1ttpGS7Y1bnO123NGGuHv9G7jiFJ+nF6Q7Vjo458XOxJ6Tp2Olr+11YHY+9A55151cbGVFRv/Zj7axfCd+
      ufffmIhIO6yOHm/kXy4Z1UVsqjyNPKUBZkpEFBSXA616AC6caOzB/Tc8p6wXzhOZE1zNkYPI4tw5949HDdyu79SuJkDIjFlCZ8M/KFWNonO7orPmmI
      g2sL8=
