language: generic
sudo: false

services:
- mysql

addons:
  ssh_known_hosts: balticrobo.eu

before_install:
- php -v
- node -v
- mysql -uroot -v

install:
- composer install
- yarn install
- cd _mail && yarn install

before_script:
- composer outdated
- yarn outdated
- cd _mail && yarn outdated
- mysql -uroot -e "CREATE DATABASE project CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

script:
- php bin/console lint:yaml config
- php bin/console lint:yaml translations
- php bin/console lint:twig templates
- php vendor/bin/phpcs -p src
- php vendor/bin/php-cs-fixer fix src --dry-run --diff -vvv
- echo 'Run tests! NOW!'

after_success:
- composer install --no-dev --optimize-autoloader --no-scripts --no-suggest
- php bin/console assets:install
- yarn install
- node assets.config.js
- yarn build
- cd _mail
- yarn install
- yarn build
- cd ..
- mkdir -p ${TRAVIS_BUILD_DIR}/dist
- cp -r bin config public src templates translations vendor composer.json composer.lock ${TRAVIS_BUILD_DIR}/dist

before_deploy:
- tar -zcvf ${TRAVIS_BUILD_DIR}/dist.tar.gz .
- openssl aes-256-cbc -K ${encrypted_a54708e5d9c1_key} -iv ${encrypted_a54708e5d9c1_iv} -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- "echo '{\"version\": \"'\"${CI_COMMIT_SHA}\"'\"}' >> version.json"
- "curl ${DEPLOY_SENTRY_RELEASE_WEBHOOK_ADDRESS} -X POST -H 'Content-Type: application/json' -d @version.json"

deploy:
- provider: script
  skip_cleanup: true
  script: mkdir -p ${TRAVIS_BUILD_DIR}/dist/var/cache &&
    chmod -R 777 ${TRAVIS_BUILD_DIR}/dist/var &&
    rsync -a --delete --exclude ".env" --exclude "public/upload"
    --rsh="ssh -o BatchMode=yes -o StrictHostKeyChecking=no"
    ${TRAVIS_BUILD_DIR}/dist/ ${PROD_HOST}:${PROD_DIRECTORY} &&
    ssh -o StrictHostKeyChecking=no ${PROD_HOST} "
    sed -i '/COMMIT_SHA/c\COMMIT_SHA=${CI_COMMIT_SHA}' ${PROD_DIRECTORY}/.env &&
    php ${PROD_DIRECTORY}/bin/console cache:clear &&
    php ${PROD_DIRECTORY}/bin/console cache:warmup &&
    php ${PROD_DIRECTORY}/bin/console doctrine:migrations:migrate --no-interaction"
  on:
    tags: true
- provider: releases
  api_key:
    secure: SicrIqCm0LcWuHeAi57TsHLfwMiV+pXY+iFjdyDjGSWI6sDF1BMzwqRq4T/p47l0l3bQMF6Z8qxJciBtoL3fUqvpgfjuLcP0Epej0mHVLySP5NHBFZhKThXCEVl94SmtCqZmwlr575l8I8omuSSAOjAm44pgTLTcVNTWQuG27jGmHEJGoWmSoTWLNlFLw8T3YH2rFHRJbUsf0e5VIE0VGGVCCyX8qatTS7TPVIaLTSYp607G0P8jBDm1JHX6Fqp+6goMayd85QM1Ag5AdJSGX2BvQ+9fyb0+42QPAxGM1mXOpsl1DLovpUz3YQDnWHBQXUVyonH+QrjmGlrLVF1q4yY8DokR997MSBsSSCcXJ+6odhBa60Uv3HSQF4Ick1LLYWEg2N5vqa9iSF55JJFE/pWrBmwc1c1kenCyxwWJPPUjr5zxQ+29OYSgB7l3MkzvBDuGInpaxskXLcRYIYNJF6Q6pWsvsMAEd4Y+TDLw4aO46QW5gg5mr8eQWJl4ahVV4kRAS30iVWWzn8PMZUTWHXsPGs9WNUnIgJ6GGl8olKicNjqlo7Chcc3B8bnLuAD8x7QeU/Iqf+c0viWcTNzkgPDg+r23tWFW97FJQZIep2ZIbQ6AtK4tLa6bjcVrJIhDBmRCtqlo0x4HJXd6v1czAky0KQRWR6vOm4eO/qfPpmU=
  skip_cleanup: true
  file: ${TRAVIS_BUILD_DIR}/dist.tar.gz
  on:
    tags: true
