version: '3.4'

services:
  php:
    build: ./.misc/docker/php
    volumes:
    - .:/var/www/app
    working_dir: /var/www/app
  node_assets:
    build: ./.misc/docker/node_assets
    volumes:
    - .:/var/www/app
    working_dir: /var/www/app
  nginx:
    image: nginx:1.15
    volumes:
    - ./public:/var/www/app/public
    - ./.misc/docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8000:80
    working_dir: /var/www/app/public
  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    - ./.misc/docker/mysql/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: balticrobo
    ports:
    - 3306:3306
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
    - 8001:8025
    logging:
      driver: none
  node_inky:
    build: ./.misc/docker/node_inky
    user: node
    volumes:
    - ./_mail:/var/www/app/_mail
    - ./public:/var/www/app/public
    - ./templates/_mail:/var/www/app/templates/_mail
    environment:
      DEPLOY_EMAIL_ASSETS_DOMAIN: http://localhost:8000/email/
    ports:
    - 8002:3000
    working_dir: /var/www/app/_mail
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: mysql
    ports:
    - 8003:80

volumes:
  mysql_data:
