version: '3.4'

services:
  prod_php:
    build: ./.misc/docker-prod/php
    volumes:
    - .:/var/www/app
    environment:
      APP_ENV: prod
    working_dir: /var/www/app
  prod_node:
    build: ./.misc/docker-prod/node
    volumes:
    - .:/var/www/app
    environment:
      DEPLOY_EMAIL_ASSETS_DOMAIN: ${PROD_EMAIL_ASSETS_DOMAIN}
    working_dir: /var/www/app
