version: '3.5'

services:
  php:
    build: ./.misc/docker/php
    volumes:
    - .:/app
  node_assets:
    build: ./.misc/docker/node_assets
    volumes:
    - .:/app
  nginx:
    build: ./.misc/docker/nginx
    volumes:
    - ./public:/app/public
    ports:
    - 8000:8000
  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: balticrobo
    ports:
    - 3306:3306
  node_inky:
    build: ./.misc/docker/node_inky
    volumes:
    - ./_mail:/app/_mail
    - ./public:/app/public
    - ./templates/_mail:/app/templates/_mail
    environment:
      DEPLOY_EMAIL_ASSETS_DOMAIN: http://localhost:8000/email/
    ports:
    - 8001:3000
  mailhog:
    image: mailhog/mailhog
    ports:
    - 8002:8025
    logging:
      driver: none
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: mysql
    ports:
    - 8003:80
    logging:
      driver: none

volumes:
  mysql_data:
