version: '3.4'

services:
  php:
    build: ./.misc/docker/php
    volumes:
    - .:/var/www/app
    - ./.misc/docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./.misc/docker/php:/opt/docker
    working_dir: /var/www/app
    command: /opt/docker/start.sh
  node_assets:
    image: node:10
    user: node
    volumes:
    - .:/var/www/app
    - ./.misc/docker/node_assets:/opt/docker
    working_dir: /var/www/app
    command: /opt/docker/start.sh
  nginx:
    image: nginx:1.15
    depends_on:
    - php
    volumes:
    - ./public:/var/www/app/public
    - ./.misc/docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8000:80
    working_dir: /var/www/app/public
  mysql:
    image: mysql:8.0
    volumes:
    - mysql_data:/var/lib/mysql
    - ./.misc/docker/mysql/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: balticrobo
    ports:
    - 3306:3306
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
    - 8001:8025
    logging:
      driver: none
  node_inky:
    build: ./.misc/docker/node_inky
    user: node
    volumes:
    - ./_mail:/var/www/app/_mail
    - ./public:/var/www/app/public
    - ./templates/_mail:/var/www/app/templates/_mail
    - ./.misc/docker/node_inky:/opt/docker
    environment:
      DEPLOY_EMAIL_ASSETS_DOMAIN: http://localhost:8000/email/
    ports:
    - 8002:3000
    working_dir: /var/www/app/_mail
    command: /opt/docker/start.sh
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: mysql
    ports:
    - 8003:80

volumes:
  mysql_data:
