services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BalticRobo\Website\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Kernel.php}'

  BalticRobo\Website\Controller\:
    resource: '../src/Controller'
    tags:
      - 'controller.service_arguments'

  BalticRobo\Website\Service\LocaleService:
    arguments:
      $availableLocales: '%available_locales%'

  BalticRobo\Website\EventListener\LocaleListener:
    arguments:
      $defaultLocale: '%locale%'
      $availableLocales: '%available_locales%'

  BalticRobo\Website\EventListener\LoginListener:
    tags:
      - { name: 'kernel.event_listener', event: 'security.interactive_login' }
